import type { User, Book, Genre, Library, Inventory } from "@/lib/types";
import { placeholderImages } from "./placeholder-images.json";
import { add } from "date-fns";

export const users: User[] = [
  {
    id: "user1",
    username: "JaneDoe",
    email: "jane.doe@example.com",
    role: "standard",
    rentedBooks: [
      { bookId: "book2", libraryId: "lib1", dueDate: add(new Date(), { days: 5 }).toISOString() },
      { bookId: "book3", libraryId: "lib2", dueDate: add(new Date(), { days: 12 }).toISOString() },
    ],
  },
  {
    id: "user2",
    username: "AdminUser",
    email: "admin@libwise.com",
    role: "admin",
    rentedBooks: [],
    libraryId: "lib1",
  },
];

export const genres: Genre[] = [
  { id: "g1", type: "Fiction" },
  { id: "g2", type: "Science Fiction" },
  { id: "g3", type: "Fantasy" },
  { id: "g4", type: "Mystery" },
  { id: "g5", type: "Romance" },
  { id: "g6", type: "Thriller" },
  { id: "g7", type: "Non-Fiction" },
  { id: "g8", type: "Biography" },
];

export const books: Book[] = [
  {
    id: "book1",
    title: "The Azure Cipher",
    author: "Evelyn Hayes",
    coverUrl: placeholderImages[0].imageUrl,
    synopsis: "A thrilling adventure to uncover an ancient secret encoded in the stars. A must-read for fans of cosmic mysteries.",
    pages: 320,
    releaseDate: "2023-05-15",
    genreIds: ["g2", "g4"],
    isActive: true,
  },
  {
    id: "book2",
    title: "Whispers of the Weeping Willow",
    author: "Samuel Reed",
    coverUrl: placeholderImages[1].imageUrl,
    synopsis: "In a quiet town, a mystical tree holds the key to a family's past and a young woman's destiny.",
    pages: 280,
    releaseDate: "2022-11-01",
    genreIds: ["g1", "g3"],
    isActive: true,
  },
  {
    id: "book3",
    title: "The Clockwork Heart",
    author: "Isabella Rossi",
    coverUrl: placeholderImages[2].imageUrl,
    synopsis: "A tale of love and loss in a steampunk city powered by intricate clockwork and hidden desires.",
    pages: 450,
    releaseDate: "2024-01-20",
    genreIds: ["g1", "g5"],
    isActive: true,
  },
  {
    id: "book4",
    title: "Echoes in the Static",
    author: "Daniel Chen",
    coverUrl: placeholderImages[3].imageUrl,
    synopsis: "A detective haunted by his past tunes into a mysterious radio frequency that broadcasts messages from another dimension.",
    pages: 390,
    releaseDate: "2023-09-10",
    genreIds: ["g2", "g6"],
    isActive: true,
  },
  {
    id: "book5",
    title: "The Last Tea Shop",
    author: "Amelia Vance",
    coverUrl: placeholderImages[4].imageUrl,
    synopsis: "A heartwarming story about a magical tea shop that serves brews capable of healing emotional wounds.",
    pages: 250,
    releaseDate: "2021-07-22",
    genreIds: ["g1", "g5"],
    isActive: true,
  },
  {
    id: "book6",
    title: "Gears of Destiny",
    author: "Julian Croft",
    coverUrl: placeholderImages[5].imageUrl,
    synopsis: "An inventor discovers a device that can alter fate, but every change comes with a dire consequence.",
    pages: 512,
    releaseDate: "2023-03-30",
    genreIds: ["g2", "g3"],
    isActive: true,
  },
  {
    id: "book7",
    title: "Neon City Blues",
    author: "Kenji Tanaka",
    coverUrl: placeholderImages[6].imageUrl,
    synopsis: "In a cyber-punk metropolis, a rogue android fights for its freedom against a powerful corporation.",
    pages: 420,
    releaseDate: "2024-02-14",
    genreIds: ["g2"],
    isActive: true,
  },
  {
    id: "book8",
    title: "The Archivist's Legacy",
    author: "Eleanor Vance",
    coverUrl: placeholderImages[7].imageUrl,
    synopsis: "A librarian discovers a hidden archive that contains the true history of the world, a truth many would kill to protect.",
    pages: 340,
    releaseDate: "2022-08-19",
    genreIds: ["g4", "g6"],
    isActive: false,
  },
  {
    id: "book9",
    title: "Voyage of the North Star",
    author: "Marcus Thorne",
    coverUrl: placeholderImages[8].imageUrl,
    synopsis: "A grand adventure on the high seas, following a crew of explorers charting unknown territories.",
    pages: 480,
    releaseDate: "2020-10-05",
    genreIds: ["g1", "g7"],
    isActive: true,
  },
  {
    id: "book10",
    title: "The Dragon's Gambit",
    author: "Seraphina Wu",
    coverUrl: placeholderImages[9].imageUrl,
    synopsis: "In a realm of magic and myth, a young sorceress must outwit a cunning dragon to save her kingdom.",
    pages: 380,
    releaseDate: "2023-11-21",
    genreIds: ["g3"],
    isActive: true,
  },
  {
    id: "book11",
    title: "The Philosopher's Mountain",
    author: "Arthur Pendelton",
    coverUrl: placeholderImages[10].imageUrl,
    synopsis: "A journey of self-discovery and enlightenment as a young thinker climbs a legendary mountain.",
    pages: 220,
    releaseDate: "2019-04-12",
    genreIds: ["g7", "g8"],
    isActive: true,
  },
  {
    id: "book12",
    title: "Case of the Crimson Quill",
    author: "Agatha Bishop",
    coverUrl: placeholderImages[11].imageUrl,
    synopsis: "A classic whodunit mystery where a famous novelist is found dead, and the only clue is a crimson quill.",
    pages: 310,
    releaseDate: "2022-01-15",
    genreIds: ["g4"],
    isActive: true,
  },
];

export const libraries: Library[] = [
  { id: "lib1", name: "Central City Library", location: "Downtown" },
  { id: "lib2", name: "Oakwood Branch", location: "Suburbs" },
  { id: "lib3", name: "Riverfront Reading Room", location: "By the river" },
];

export const inventory: Inventory[] = [
  ...books.map(book => ({
    id: `inv_${book.id}_lib1`,
    bookId: book.id,
    libraryId: "lib1",
    status: book.id === "book2" ? 'rented' : 'available',
    currentUserId: book.id === "book2" ? 'user1' : null,
  } as Inventory)),
  ...books.slice(0, 6).map(book => ({
    id: `inv_${book.id}_lib2`,
    bookId: book.id,
    libraryId: "lib2",
    status: book.id === "book3" ? 'rented' : 'available',
    currentUserId: book.id === "book3" ? 'user1' : null,
  } as Inventory)),
  ...books.slice(5).map(book => ({
    id: `inv_${book.id}_lib3`,
    bookId: book.id,
    libraryId: "lib3",
    status: 'available',
    currentUserId: null,
  } as Inventory)),
];
